version: "3"

services:
  app:
    build: .
    image: joaoduarte10/desafio-full-cycle-docker-node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: npm run start
    expose:
      - 3000
    depends_on:
      - db
    networks:
      - node-network
    tty: true
    volumes:
      - .:/usr/src/app
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=node_database
      - MYSQL_ROOT_PASSWORD=node_password
    volumes:
      - ./data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - node-network
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - node-network

networks:
  node-network:
    external: false
